//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NebulaSmite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NebulaSmite.Resources.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otomatik.
        /// </summary>
        internal static string Label_Auto {
            get {
                return ResourceManager.GetString("Label_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destansi yaratik / Canavar etrafindaki dusman / Sampiyon oldur yada son vurus.
        /// </summary>
        internal static string Label_Auto_1 {
            get {
                return ResourceManager.GetString("Label_Auto_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by TekinTR.
        /// </summary>
        internal static string Label_By {
            get {
                return ResourceManager.GetString("Label_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oyuncu ve canavar etrafindaki dusman kontrol araligi.
        /// </summary>
        internal static string Label_CheckEnemy {
            get {
                return ResourceManager.GetString("Label_CheckEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusman sagligi [ n% ] dan daha dusukse.
        /// </summary>
        internal static string Label_CheckHP {
            get {
                return ResourceManager.GetString("Label_CheckHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goster [ % ] Hasar.
        /// </summary>
        internal static string Label_Draw_DmgP {
            get {
                return ResourceManager.GetString("Label_Draw_DmgP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menzil goster.
        /// </summary>
        internal static string Label_Draw_Range {
            get {
                return ResourceManager.GetString("Label_Draw_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canavar.
        /// </summary>
        internal static string Label_Monster {
            get {
                return ResourceManager.GetString("Label_Monster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carp.
        /// </summary>
        internal static string Label_Smite {
            get {
                return ResourceManager.GetString("Label_Smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampiyon.
        /// </summary>
        internal static string Label_Smite_C {
            get {
                return ResourceManager.GetString("Label_Smite_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orman.
        /// </summary>
        internal static string Label_Smite_J {
            get {
                return ResourceManager.GetString("Label_Smite_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil ( Korece )  /  Aktiflestir : F5.
        /// </summary>
        internal static string Main_Language_Select {
            get {
                return ResourceManager.GetString("Main_Language_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapimci goldfish. .
        /// </summary>
        internal static string Main_Text_1 {
            get {
                return ResourceManager.GetString("Main_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkce Ceviri TekinTR - Herhangi bir problemde benimle iletisime gecin..
        /// </summary>
        internal static string Main_Text_2 {
            get {
                return ResourceManager.GetString("Main_Text_2", resourceCulture);
            }
        }
    }
}
